version: '3.8'

services:

  back_end:
    container_name: edcartel__back_end
    build:
      context: .
      dockerfile: Dockerfile
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8088 -Djava.security.egd=file:/dev/./urandom -jar build/libs/EdCartel.jar
    restart: on-failure
    working_dir: /EdCartel
    volumes:
      - .:/EdCartel
    ports:
      - 9696:9696
    links:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  db:
    container_name: edcartel__back_end__database
    image: postgres:12.2-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: userDB
      POSTGRES_PASSWORD: userDB
