GET localhost:9696/role/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODY3MzMwNDEsInVzZXJfbmFtZSI6ImFsZXgiLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImEyMzA2OTM5LTlhMjgtNGIyOC1hOTViLTM3YzgwNDNlYWFhYiIsImNsaWVudF9pZCI6InZ1ZS1jbGllbnQiLCJzY29wZSI6WyJhbnkiXX0.a0cp1ANzTMZSsX1lDTqnhzsr5zpIdVEwigdei7G9XgM

###
