
#####
POST tut:tut@localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=alex&password=alex&scope=all

#####
POST tut:tut@localhost:8080/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODMwODIyMDYsInVzZXJfbmFtZSI6ImFsZXgiLCJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJqdGkiOiI5YjM5NDczNy0xNDI0LTQxMGUtODk0NC1lMTkyYTU1N2NjYmUiLCJjbGllbnRfaWQiOiJ0dXQiLCJzY29wZSI6WyJhbGwiXX0.mv78edhe7DVPFS5Oc6sDQv5J6Z4ISh2SBYGxNBUzz5I
Content-Type: application/x-www-form-urlencoded

#####
GET tut:tut@localhost:8080/oauth/token_key
Content-Type: application/x-www-form-urlencoded



#####
POST localhost:8080/oauth/authorize?client_id=tut&response_type=code&scope=all
Content-Type: application/x-www-form-urlencoded

username=alex&password=alex

###

POST tut:tut@localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=all

###

