
GET localhost:8080/user/find-all
Content-Type: application/json
Authorization: Basic ZGFuaWVsOmRhbmllbA==


####

POST localhost:8080/user/create
Content-Type: application/json

{
  "userName": "qweqweqwe",
  "passWord": "qweqweqwe",
  "firstName": "qweqwe",
  "familyName": "qweqwe",
  "roles": "USER"
}

####

POST localhost:8080/user/create
Content-Type: application/json
Authorization: Basic YWxleDphbGV4

{
  "userName": "qweqweqwe",
  "passWord": "qweqweqwe",
  "firstName": "qweqweqwe",
  "familyName": "qweqweqwe",
  "roles": ["USER", "ADMIN"]
}

###