#debug: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  main:
    lazy-initialization: true
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:5432/testDB"
    name: "testDB"
    username: "userDB"
    password: "userDB"
    initialization-mode: always
  jpa:
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    actuator-metrics: true
  tools:
    schema-location-pattern: "**/*.graphql"

